name: 'Jekyll Webpack Build System'
description: 'Run a command on the build system'
inputs:
  command-to-run:  # id of input
    description: 'Command to run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command-to-run }}
